### ISSUE TITLE
stops after 1 check

### ISSUE THREAD

**Issue by just-rich** [verfasor/twitter-handle-checker#1]
_I'm not a dev, but can easily follow directions and fill out a config, so don't mind my ignorance_

Isn't it supposed to continue monitoring and check every 5 minutes? I see the 300second timer, but when starting it, completes 1 check, then after 5 minutes it quits.

Shouldn't it continue monitoring and check every 5min?

**Comment by just-rich** [comment]
Well I just added `check_user(username)` on the last line after the one there already, seems to work fine now.

Edit: nevermind, just checked twice then stopped

**Comment by verfasor** [comment]
Hi Rich, I've updated the script. Check the revised version of [twitter-checker-mail.py](https://github.com/verfasor/twitter-handle-checker/blob/main/twitter-checker-mail.py). Added `schedule` dependency as well. So you have to `pip install schedule` or `pip3 install schedule` before running the script.

**Comment by just-rich** [comment]
Much appreciated!

SoI pulled, installed `schedule`, and ran it. looks like its good. will it show any type of logs, like when it checks every 5 minutes saying what the status of the account is? cause I haven't seen that yet. or will it just run without logs and only send an email when it detects the username is available?

thanks again!

**Comment by verfasor** [comment]
It does show the current status every 5 minutes in the terminal: 

The script is set to print **"The twitter handle @{username} is active"** 

OR

**"The twitter handle @{username} is still suspended."** in the terminal during each check. 

And once the username is available,  it'll print: 

**"The twitter handle @{username} does not exist. Go get it now! 
Mail sent."** and sends an email.

**Comment by just-rich** [comment]
Awesome, yep I see that now. Appreciate you brotha!!
